# Generated by Django 2.2.7 on 2019-11-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='resign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
